matrix:
  include:
    - language: go
      go: 
        - 1.14.x
      env:
        - GO111MODULE=on
      before_script:
        - cd server
      script:
        - go build .

    - language: node_js
      node_js:
        - 14
      install:
        - npm install -g rollup
        - npm install
      before_script:
        - cd web
      script:
        - npm run build

notifications:
  email:
    - 930372551@qq.com

services:
  - mongodb