# Shadow Editor Server Configuration

[server]
port = ":2020"                              # server address

[database]
type = "mongo"                              # only support mongo
host = "127.0.0.1"                          # mongoDB host
port = 27017                                # mongoDB port
database = "ShadowEditorDemo"                   # mongoDB database name

[authority]
enabled = false                              # enable authority
expires = 120                               # login time, minutes, only support integer 

[upload]
max_size = 1000000000                       # max upload file size

[remote]
enabled = false                             # enable remote edit
web_socket_port = 5000                      # web socket server port

[path]
public_dir = "../build/public"                     # The directory that contains index.html. 
                                            # Path `./public/Upload` need write authority.
log_dir = "./logs"                          # The directory that contains log files. Need write authority.

[log]
file = "./logs/ShadowServer.txt"